# Generated by Django 4.2.23 on 2025-09-10 08:07

import api.models
from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('doctor', 'Doctor'), ('patient', 'Patient')], default='patient', max_length=20)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('hospital_id', models.CharField(blank=True, max_length=100, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mrn', models.CharField(max_length=64, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=80, null=True)),
                ('last_name', models.CharField(blank=True, max_length=80, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=12, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('comorbidities', models.JSONField(blank=True, help_text="e.g. ['DM','PAD']", null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctors', models.ManyToManyField(blank=True, limit_choices_to={'role': 'doctor'}, related_name='assigned_patients', to=settings.AUTH_USER_MODEL)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Wound',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wound_type', models.CharField(choices=[('DFU', 'Diabetic Foot Ulcer'), ('PVD', 'Peripheral Vascular Disease Ulcer'), ('POST_OP', 'Post-Operative Wound'), ('TRAUMA', 'Trauma'), ('OTHER', 'Other')], default='OTHER', max_length=20)),
                ('body_location', models.CharField(blank=True, max_length=120, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('latest_status', models.CharField(blank=True, max_length=120, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_wounds', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wounds', to='api.patient')),
            ],
        ),
        migrations.CreateModel(
            name='WoundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_wound_image_path)),
                ('plotted_image', models.ImageField(blank=True, null=True, upload_to=api.models.upload_wound_image_path)),
                ('notes', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('width_px', models.IntegerField(blank=True, null=True)),
                ('height_px', models.IntegerField(blank=True, null=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_wound_images', to=settings.AUTH_USER_MODEL)),
                ('wound', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='api.wound')),
            ],
        ),
        migrations.CreateModel(
            name='WoundAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_wound', models.BooleanField(default=True)),
                ('rejection_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('wound_area_cm2', models.FloatField(blank=True, null=True)),
                ('length_cm', models.FloatField(blank=True, null=True)),
                ('width_cm', models.FloatField(blank=True, null=True)),
                ('estimated_depth_mm', models.FloatField(blank=True, null=True)),
                ('perimeter_cm', models.FloatField(blank=True, null=True)),
                ('volume_cm3', models.FloatField(blank=True, null=True)),
                ('tissue_type', models.JSONField(blank=True, null=True)),
                ('exudate', models.CharField(blank=True, max_length=120, null=True)),
                ('odor', models.CharField(blank=True, max_length=120, null=True)),
                ('periwound_skin', models.CharField(blank=True, max_length=120, null=True)),
                ('healing_stage', models.CharField(blank=True, max_length=120, null=True)),
                ('classification', models.CharField(blank=True, max_length=120, null=True)),
                ('healing_index', models.FloatField(blank=True, null=True)),
                ('recommendations', models.JSONField(blank=True, null=True)),
                ('potential_complications', models.JSONField(blank=True, null=True)),
                ('analysis_summary', models.TextField(blank=True, null=True)),
                ('wound_outline_coordinates', models.JSONField(blank=True, null=True)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('wound_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='analysis', to='api.woundimage')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(blank=True, null=True, upload_to=api.models.reports_upload_path)),
                ('file_base64', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_id', models.CharField(db_index=True, max_length=64)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('uploaded', 'Uploaded'), ('shared', 'Shared')], default='draft', max_length=32)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_reports', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.patient')),
                ('shared_with', models.ManyToManyField(blank=True, limit_choices_to={'role': 'doctor'}, related_name='shared_reports', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('ai_suggestion', models.JSONField(blank=True, null=True)),
                ('clinician_review', models.JSONField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('ai_generated', 'AI Generated'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('model_version', models.CharField(blank=True, max_length=64, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('hospital_id', models.CharField(db_index=True, max_length=64)),
                ('doctor', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='api.patient')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_prescriptions', to=settings.AUTH_USER_MODEL)),
                ('wound', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.wound')),
            ],
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=128)),
                ('entity', models.CharField(max_length=128)),
                ('entity_id', models.CharField(blank=True, max_length=64, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
