# Generated by Django 4.2.23 on 2025-06-27 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='woundimage',
            name='plotted_image',
            field=models.ImageField(blank=True, null=True, upload_to='wound_plots/'),
        ),
    ]
