# Generated by Django 4.2.23 on 2025-08-21 11:28

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('api', '0002_woundimage_plotted_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='woundimage',
            old_name='capture_date',
            new_name='uploaded_at',
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='wound_care_users', related_query_name='wound_care_user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('patient', 'Patient'), ('doctor', 'Doctor'), ('admin', 'Admin')], default='patient', max_length=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='wound_care_users', related_query_name='wound_care_user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='woundanalysis',
            name='exudate',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='woundanalysis',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='woundanalysis',
            name='potential_complications',
            field=models.JSONField(blank=True, help_text="JSON array: ['Infection Risk', 'Delayed Healing']", null=True),
        ),
        migrations.AlterField(
            model_name='woundanalysis',
            name='recommendations',
            field=models.JSONField(blank=True, help_text="JSON array: ['Cleanse daily', 'Apply dressing']", null=True),
        ),
        migrations.AlterField(
            model_name='woundanalysis',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='woundanalysis',
            name='tissue_type',
            field=models.JSONField(blank=True, help_text="JSON object: {'Slough': 'X%', 'Necrosis': 'Y%', ...}", null=True),
        ),
        migrations.AlterField(
            model_name='woundanalysis',
            name='wound_outline_coordinates',
            field=models.JSONField(blank=True, help_text='JSON array of [x, y] coordinates for wound outline', null=True),
        ),
        migrations.AlterField(
            model_name='woundimage',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='woundimage',
            name='image',
            field=models.ImageField(upload_to='wound_images/'),
        ),
        migrations.AlterField(
            model_name='woundimage',
            name='plotted_image',
            field=models.ImageField(blank=True, help_text='Image with ML analysis plotted (e.g., 3D visualization, segmentation overlay)', null=True, upload_to='plotted_wound_images/'),
        ),
    ]
