# Generated by Django 4.2.23 on 2025-08-21 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_capture_date_woundimage_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woundanalysis',
            name='tissue_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
