# Generated by Django 4.2.23 on 2025-08-21 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_alter_woundanalysis_tissue_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='woundanalysis',
            name='tissue_type',
            field=models.JSONField(blank=True, max_length=100, null=True),
        ),
    ]
